export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface OperationField {
  name: string
  label: string
  placeholder?: string
}

export interface ApiOperation {
  id: string
  domain: string
  title: string
  method: HttpMethod
  path: string
  auth?: boolean
  pathParams?: OperationField[]
  queryParams?: OperationField[]
  bodyTemplate?: unknown
}

export const apiOperations: ApiOperation[] = [
  {
    id: 'system-health',
    domain: 'Dashboard',
    title: '健康检查',
    method: 'GET',
    path: '/health',
    auth: false,
  },
  {
    id: 'dashboard-overview',
    domain: 'Dashboard',
    title: '系统总览',
    method: 'GET',
    path: '/dashboard/overview',
  },
  {
    id: 'identity-list-roles',
    domain: 'Identity',
    title: '角色列表',
    method: 'GET',
    path: '/roles',
    auth: false,
  },
  {
    id: 'identity-register-agent',
    domain: 'Identity',
    title: '注册 AI Agent',
    method: 'POST',
    path: '/agents/register',
    bodyTemplate: {
      name: 'Finance Analyst Agent',
      model_type: 'gpt-4.1',
      capabilities: ['analysis', 'reporting'],
      permission_level: 'L2',
      agent_origin: 'internal',
      provider: 'OpenAI',
      service_class: 'model',
      vendor: '',
      contract_ref: '',
      risk_level: 'medium',
      metadata: {},
    },
  },
  {
    id: 'identity-list-agents',
    domain: 'Identity',
    title: 'Agent 列表',
    method: 'GET',
    path: '/agents',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'identity-agent-auth',
    domain: 'Identity',
    title: 'Agent 鉴权',
    method: 'POST',
    path: '/agents/auth',
    auth: false,
    bodyTemplate: {
      agent_id: '',
      api_key: '',
    },
  },
  {
    id: 'organization-create',
    domain: 'Organization',
    title: '创建组织',
    method: 'POST',
    path: '/organizations',
    bodyTemplate: {
      name: 'Harness Company',
      description: 'Self evolving operating system',
    },
  },
  {
    id: 'organization-list',
    domain: 'Organization',
    title: '组织列表',
    method: 'GET',
    path: '/organizations',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'organization-current',
    domain: 'Organization',
    title: '当前组织',
    method: 'GET',
    path: '/organization/current',
  },
  {
    id: 'organization-get',
    domain: 'Organization',
    title: '组织详情',
    method: 'GET',
    path: '/organizations/{id}',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'organization-update',
    domain: 'Organization',
    title: '修改组织',
    method: 'PATCH',
    path: '/organizations/{id}',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    bodyTemplate: {
      name: 'Harness Company',
      description: 'Updated organization profile',
    },
  },
  {
    id: 'department-create',
    domain: 'Organization',
    title: '创建部门',
    method: 'POST',
    path: '/organizations/{id}/departments',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    bodyTemplate: {
      name: 'Product Engineering',
      code: 'ENG',
      description: 'Product and platform engineering',
      status: 'active',
      sort_order: 10,
      parent_id: null,
      metadata: {},
    },
  },
  {
    id: 'department-list',
    domain: 'Organization',
    title: '部门列表',
    method: 'GET',
    path: '/organizations/{id}/departments',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'department-tree',
    domain: 'Organization',
    title: '部门树',
    method: 'GET',
    path: '/organizations/{id}/departments/tree',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'department-get',
    domain: 'Organization',
    title: '部门详情',
    method: 'GET',
    path: '/departments/{id}',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'department-update',
    domain: 'Organization',
    title: '更新部门',
    method: 'PATCH',
    path: '/departments/{id}',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      name: 'Product Engineering',
      description: 'Updated department profile',
      status: 'active',
      sort_order: 20,
      metadata: {},
    },
  },
  {
    id: 'position-create',
    domain: 'Organization',
    title: '创建岗位',
    method: 'POST',
    path: '/departments/{id}/positions',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      name: 'Workflow Owner',
      code: 'WF_OWNER',
      description: 'Own workflow planning and node accountability',
      permission_level: 'L2',
      required_capabilities: ['planning', 'review'],
      status: 'active',
      sort_order: 10,
      metadata: {},
    },
  },
  {
    id: 'position-list-by-department',
    domain: 'Organization',
    title: '部门岗位列表',
    method: 'GET',
    path: '/departments/{id}/positions',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'position-get',
    domain: 'Organization',
    title: '岗位详情',
    method: 'GET',
    path: '/positions/{id}',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
  },
  {
    id: 'position-update',
    domain: 'Organization',
    title: '更新岗位',
    method: 'PATCH',
    path: '/positions/{id}',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
    bodyTemplate: {
      name: 'Workflow Owner',
      description: 'Updated position profile',
      permission_level: 'L3',
      required_capabilities: ['planning', 'approval', 'review'],
      status: 'active',
      sort_order: 20,
      metadata: {},
    },
  },
  {
    id: 'position-assignment-create',
    domain: 'Organization',
    title: '创建岗位适配',
    method: 'POST',
    path: '/positions/{id}/assignments',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      assignment_type: 'primary',
      allocation_percent: 100,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'position-assignment-list',
    domain: 'Organization',
    title: '岗位适配列表',
    method: 'GET',
    path: '/positions/{id}/assignments',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
  },
  {
    id: 'position-assignment-update',
    domain: 'Organization',
    title: '更新岗位适配',
    method: 'PATCH',
    path: '/position-assignments/{id}',
    pathParams: [{ name: 'id', label: '岗位适配 ID' }],
    bodyTemplate: {
      assignment_type: 'backup',
      allocation_percent: 50,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'position-assignment-remove',
    domain: 'Organization',
    title: '移除岗位适配',
    method: 'DELETE',
    path: '/position-assignments/{id}',
    pathParams: [{ name: 'id', label: '岗位适配 ID' }],
  },
  {
    id: 'external-member-create',
    domain: 'Organization',
    title: '创建外部成员',
    method: 'POST',
    path: '/external-members',
    bodyTemplate: {
      name: 'External Consultant',
      email: 'consultant@example.com',
      vendor: 'Partner Co',
      contract_type: 'advisor',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'external-member-list',
    domain: 'Organization',
    title: '外部成员列表',
    method: 'GET',
    path: '/external-members',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'external-member-get',
    domain: 'Organization',
    title: '外部成员详情',
    method: 'GET',
    path: '/external-members/{id}',
    pathParams: [{ name: 'id', label: '外部成员 ID' }],
  },
  {
    id: 'external-member-update',
    domain: 'Organization',
    title: '更新外部成员',
    method: 'PATCH',
    path: '/external-members/{id}',
    pathParams: [{ name: 'id', label: '外部成员 ID' }],
    bodyTemplate: {
      vendor: 'Partner Co',
      contract_type: 'delivery',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'organization-members',
    domain: 'Organization',
    title: '组织成员列表',
    method: 'GET',
    path: '/organizations/{id}/members',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    queryParams: [
      { name: 'department_id', label: '部门 ID' },
      { name: 'member_type', label: '成员类型', placeholder: 'internal | external | agent' },
    ],
  },
  {
    id: 'department-add-member',
    domain: 'Organization',
    title: '部门添加成员',
    method: 'POST',
    path: '/departments/{id}/members',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      member_type: 'internal',
      user_id: '',
      external_member_id: null,
      agent_id: null,
      title: 'Engineering Lead',
      role_id: null,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'department-members',
    domain: 'Organization',
    title: '部门成员列表',
    method: 'GET',
    path: '/departments/{id}/members',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    queryParams: [{ name: 'member_type', label: '成员类型', placeholder: 'internal | external | agent' }],
  },
  {
    id: 'membership-update',
    domain: 'Organization',
    title: '更新成员关系',
    method: 'PATCH',
    path: '/memberships/{id}',
    pathParams: [{ name: 'id', label: '成员关系 ID' }],
    bodyTemplate: {
      title: 'Senior Engineer',
      role_id: null,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'membership-remove',
    domain: 'Organization',
    title: '移除组织成员',
    method: 'DELETE',
    path: '/memberships/{id}',
    pathParams: [{ name: 'id', label: '成员关系 ID' }],
  },
  {
    id: 'department-link-mvru',
    domain: 'Organization',
    title: '关联部门与 MVRU',
    method: 'POST',
    path: '/departments/{id}/mvru-links',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      mvru_id: '',
      link_type: 'execution',
      metadata: {},
    },
  },
  {
    id: 'department-mvru-links',
    domain: 'Organization',
    title: '部门 MVRU 关联',
    method: 'GET',
    path: '/departments/{id}/mvru-links',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'organization-match-members',
    domain: 'Organization',
    title: '匹配成员',
    method: 'POST',
    path: '/organization/match-members',
    bodyTemplate: {
      organization_id: '',
      department_id: null,
      position_id: null,
      task_description: 'review launch readiness',
      workflow_template_id: null,
      required_capabilities: ['review'],
      required_level: 'L2',
      risk_level: 'medium',
      member_types: ['internal', 'agent'],
    },
  },
  {
    id: 'organization-match-capabilities',
    domain: 'Organization',
    title: '能力匹配桥接',
    method: 'POST',
    path: '/organization/match-capabilities',
    bodyTemplate: {
      department_id: null,
      task_description: 'review launch readiness',
      required_capabilities: ['review'],
      required_level: 'L2',
      risk_level: 'medium',
      context: {},
    },
  },
  {
    id: 'mvru-create',
    domain: 'Organization',
    title: '创建 MVRU',
    method: 'POST',
    path: '/muvrs',
    bodyTemplate: {
      organization_id: '',
      name: 'Decision Ops',
      description: 'Decision support unit',
      boundary: {
        data_permissions: [],
        resource_quota: {},
        network_policies: [],
      },
      config: {},
      parent_id: null,
    },
  },
  {
    id: 'mvru-get',
    domain: 'Organization',
    title: 'MVRU 详情',
    method: 'GET',
    path: '/muvrs/{id}',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
  },
  {
    id: 'mvru-status',
    domain: 'Organization',
    title: '更新 MVRU 状态',
    method: 'PATCH',
    path: '/muvrs/{id}/status',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      status: 'active',
    },
  },
  {
    id: 'mvru-add-member',
    domain: 'Organization',
    title: '添加成员',
    method: 'POST',
    path: '/muvrs/{id}/members',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      user_id: '',
      agent_id: null,
      role_id: '',
    },
  },
  {
    id: 'mvru-remove-member',
    domain: 'Organization',
    title: '移除成员',
    method: 'DELETE',
    path: '/muvrs/{id}/members',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      user_id: '',
      agent_id: null,
    },
  },
  {
    id: 'relationship-create',
    domain: 'Organization',
    title: '创建 MVRU 关系',
    method: 'POST',
    path: '/relationships',
    bodyTemplate: {
      source_mvru_id: '',
      target_mvru_id: '',
      rel_type: 'collaborate',
      config: {},
    },
  },
  {
    id: 'layer-classify',
    domain: 'Layer',
    title: '任务分层',
    method: 'POST',
    path: '/layers/classify',
    bodyTemplate: {
      task_description: 'Review a strategic compliance initiative',
      complexity_score: 0.5,
      risk_score: 0.3,
      strategic_score: 0.7,
      metadata: {},
    },
  },
  {
    id: 'layer-get-config',
    domain: 'Layer',
    title: '读取层配置',
    method: 'GET',
    path: '/layers/config/{mvruId}',
    pathParams: [{ name: 'mvruId', label: 'MVRU ID' }],
    queryParams: [{ name: 'layer', label: '层级', placeholder: 'strategic | tactical | operational' }],
  },
  {
    id: 'layer-set-config',
    domain: 'Layer',
    title: '保存层配置',
    method: 'PUT',
    path: '/layers/config/{mvruId}',
    pathParams: [{ name: 'mvruId', label: 'MVRU ID' }],
    bodyTemplate: {
      layer: 'tactical',
      config: {
        routing: 'balanced',
      },
    },
  },
  {
    id: 'layer-list-rules',
    domain: 'Layer',
    title: '路由规则',
    method: 'GET',
    path: '/layers/rules',
  },
  {
    id: 'capability-create',
    domain: 'Capability',
    title: '创建能力',
    method: 'POST',
    path: '/capabilities',
    bodyTemplate: {
      name: 'summarize-report',
      version: '1.0',
      description: 'Summarize operating reports',
      input_schema: {},
      output_schema: {},
      preconditions: [],
      error_handling: {},
      permission_level: 'L2',
      cost_estimate: {},
    },
  },
  {
    id: 'capability-list',
    domain: 'Capability',
    title: '能力列表',
    method: 'GET',
    path: '/capabilities',
  },
  {
    id: 'capability-get',
    domain: 'Capability',
    title: '能力详情',
    method: 'GET',
    path: '/capabilities/{id}',
    pathParams: [{ name: 'id', label: '能力 ID' }],
  },
  {
    id: 'capability-match',
    domain: 'Capability',
    title: '能力匹配',
    method: 'POST',
    path: '/capabilities/match',
    bodyTemplate: {
      task_description: 'summarize weekly operating metrics',
      required_level: 'L2',
      metadata: {},
    },
  },
  {
    id: 'capability-create-evaluation',
    domain: 'Capability',
    title: '创建能力评估',
    method: 'POST',
    path: '/capabilities/evaluations',
    bodyTemplate: {
      capability_id: null,
      actor_id: null,
      actor_type: 'internal_agent',
      workflow_id: null,
      task_id: null,
      evaluator_id: null,
      evaluator_type: 'human',
      quality_score: 0.8,
      reliability_score: 0.75,
      cost_score: 0.7,
      latency_score: 0.7,
      risk_score: 0.65,
      compliance_score: 0.8,
      evidence: { risk_level: 'medium' },
      conclusion: 'human-reviewed capability evaluation',
    },
  },
  {
    id: 'capability-list-evaluations',
    domain: 'Capability',
    title: '能力评估列表',
    method: 'GET',
    path: '/capabilities/evaluations',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'capability-list-one-evaluations',
    domain: 'Capability',
    title: '单能力评估列表',
    method: 'GET',
    path: '/capabilities/{id}/evaluations',
    pathParams: [{ name: 'id', label: '能力 ID' }],
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'capability-bind',
    domain: 'Capability',
    title: '绑定能力',
    method: 'POST',
    path: '/bindings',
    bodyTemplate: {
      capability_id: '',
      mvru_id: '',
      config: {},
    },
  },
  {
    id: 'capability-unbind',
    domain: 'Capability',
    title: '解绑能力',
    method: 'DELETE',
    path: '/bindings/{id}',
    pathParams: [{ name: 'id', label: '绑定 ID' }],
  },
  {
    id: 'capability-list-bindings',
    domain: 'Capability',
    title: 'MVRU 绑定能力',
    method: 'GET',
    path: '/bindings',
    queryParams: [{ name: 'mvru_id', label: 'MVRU ID' }],
  },
  {
    id: 'workflow-create-template',
    domain: 'Workflow',
    title: '创建工作流模板',
    method: 'POST',
    path: '/workflows/templates',
    bodyTemplate: {
      name: 'PER Review',
      description: 'Planner Executor Reviewer workflow',
      organization_id: null,
      department_id: null,
      stages: [
        {
          id: 'plan-1',
          type: 'plan',
          name: 'Planning',
          assignee_type: 'internal',
          position_id: null,
          position_code: null,
          required_capabilities: ['planning'],
          required_permission_level: 'L1',
          required_roles: ['planner'],
          risk_level: 'low',
          preferred_actor_types: ['internal_human'],
          evaluation_policy: { primary_reviewer: 'human' },
          matching_policy: { ranking: 'capability_weight_access' },
        },
        {
          id: 'execute-1',
          type: 'execute',
          name: 'Execution',
          assignee_type: 'either',
          position_id: null,
          position_code: null,
          required_capabilities: ['execution'],
          required_permission_level: 'L2',
          required_roles: ['executor'],
          risk_level: 'medium',
          preferred_actor_types: ['internal_human', 'internal_agent'],
          evaluation_policy: { primary_reviewer: 'human' },
          matching_policy: { ranking: 'capability_weight_access' },
        },
        {
          id: 'review-1',
          type: 'review',
          name: 'Review',
          assignee_type: 'internal',
          position_id: null,
          position_code: null,
          required_capabilities: ['review'],
          required_permission_level: 'L2',
          required_roles: ['reviewer'],
          risk_level: 'medium',
          preferred_actor_types: ['internal_human'],
          evaluation_policy: { primary_reviewer: 'human', update_weight: true },
          matching_policy: { ranking: 'capability_weight_access' },
        },
      ],
      assignee_type: 'either',
      required_weight: 0.5,
      routing_rules: {},
      visual_graph: {
        nodes: [],
        edges: [],
      },
    },
  },
  {
    id: 'workflow-list-templates',
    domain: 'Workflow',
    title: '模板列表',
    method: 'GET',
    path: '/workflows/templates',
  },
  {
    id: 'workflow-get-template',
    domain: 'Workflow',
    title: '模板详情',
    method: 'GET',
    path: '/workflows/templates/{id}',
    pathParams: [{ name: 'id', label: '模板 ID' }],
  },
  {
    id: 'workflow-start',
    domain: 'Workflow',
    title: '启动工作流',
    method: 'POST',
    path: '/workflows/instances',
    bodyTemplate: {
      template_id: '',
      organization_id: null,
      department_id: null,
      project_id: null,
      context: {
        objective: 'Review launch readiness',
      },
    },
  },
  {
    id: 'workflow-get',
    domain: 'Workflow',
    title: '工作流详情',
    method: 'GET',
    path: '/workflows/instances/{id}',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
  },
  {
    id: 'workflow-status',
    domain: 'Workflow',
    title: '更新工作流状态',
    method: 'PATCH',
    path: '/workflows/instances/{id}/status',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
    bodyTemplate: {
      status: 'paused',
    },
  },
  {
    id: 'workflow-complete-task',
    domain: 'Workflow',
    title: '完成任务',
    method: 'PATCH',
    path: '/tasks/{id}/status',
    pathParams: [{ name: 'id', label: '任务 ID' }],
    bodyTemplate: {
      output: {
        summary: 'done',
      },
    },
  },
  {
    id: 'workflow-decision',
    domain: 'Workflow',
    title: '记录决策',
    method: 'POST',
    path: '/tasks/{id}/decisions',
    pathParams: [{ name: 'id', label: '任务 ID' }],
    bodyTemplate: {
      decision_maker_id: '',
      maker_type: 'human',
      reasoning: 'Weighted decision record',
      outcome: 'approved',
      input: {},
      output: {},
    },
  },
  {
    id: 'workflow-get-context',
    domain: 'Workflow',
    title: '读取上下文',
    method: 'GET',
    path: '/workflows/instances/{id}/context',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
  },
  {
    id: 'workflow-update-context',
    domain: 'Workflow',
    title: '更新上下文',
    method: 'PUT',
    path: '/workflows/instances/{id}/context',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
    bodyTemplate: {
      working_memory: {},
      injected_experience: [],
      principle_notes: '',
    },
  },
  {
    id: 'observability-start-trace',
    domain: 'Observability',
    title: '开始 Trace',
    method: 'POST',
    path: '/traces',
    bodyTemplate: {
      workflow_id: null,
      metadata: {},
    },
  },
  {
    id: 'observability-list-traces',
    domain: 'Observability',
    title: 'Trace 列表',
    method: 'GET',
    path: '/traces',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'observability-get-trace',
    domain: 'Observability',
    title: 'Trace 详情',
    method: 'GET',
    path: '/traces/{id}',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
  },
  {
    id: 'observability-record-span',
    domain: 'Observability',
    title: '记录 Span',
    method: 'POST',
    path: '/traces/{id}/spans',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
    bodyTemplate: {
      span_type: 'task',
      entity_id: null,
      entity_type: 'task',
      actor_id: null,
      actor_type: 'human',
      input: {},
      output: {},
      duration_ms: 120,
      metadata: {},
    },
  },
  {
    id: 'observability-complete-trace',
    domain: 'Observability',
    title: '完成 Trace',
    method: 'POST',
    path: '/traces/{id}/complete',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
    bodyTemplate: {
      status: 'completed',
    },
  },
  {
    id: 'observability-record-metric',
    domain: 'Observability',
    title: '记录指标',
    method: 'POST',
    path: '/metrics',
    bodyTemplate: {
      metric_type: 'health',
      metric_name: 'workflow_quality',
      entity_id: null,
      entity_type: 'workflow',
      value: 0.92,
      metadata: {},
    },
  },
  {
    id: 'observability-query-metrics',
    domain: 'Observability',
    title: '查询指标',
    method: 'GET',
    path: '/metrics',
    queryParams: [
      { name: 'metric_type', label: '类型' },
      { name: 'metric_name', label: '名称' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'verification-create-report',
    domain: 'Verification',
    title: '创建验证报告',
    method: 'POST',
    path: '/verification/reports',
    bodyTemplate: {
      workflow_id: null,
      task_id: null,
      result_score: 0.9,
      path_score: 0.8,
      environment_score: 0.85,
      conclusion: 'passed',
      suggestions: [],
    },
  },
  {
    id: 'verification-list-reports',
    domain: 'Verification',
    title: '报告列表',
    method: 'GET',
    path: '/verification/reports',
    queryParams: [
      { name: 'workflow_id', label: '工作流 ID' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'verification-get-report',
    domain: 'Verification',
    title: '报告详情',
    method: 'GET',
    path: '/verification/reports/{id}',
    pathParams: [{ name: 'id', label: '报告 ID' }],
  },
  {
    id: 'verification-assign-review',
    domain: 'Verification',
    title: '分配复核',
    method: 'POST',
    path: '/verification/reports/{id}/reviews',
    pathParams: [{ name: 'id', label: '报告 ID' }],
    bodyTemplate: {
      level: 'L1',
      reviewer_id: null,
      reviewer_type: 'machine',
    },
  },
  {
    id: 'verification-complete-review',
    domain: 'Verification',
    title: '完成复核',
    method: 'PATCH',
    path: '/verification/reviews/{id}',
    pathParams: [{ name: 'id', label: '复核 ID' }],
    bodyTemplate: {
      result: {
        status: 'approved',
      },
    },
  },
  {
    id: 'governance-create-permission',
    domain: 'Governance',
    title: '创建权限',
    method: 'POST',
    path: '/governance/permissions',
    bodyTemplate: {
      level: 2,
      name: 'workflow.execute',
      description: 'Execute workflow task',
      behavior: 'notify',
    },
  },
  {
    id: 'governance-list-permissions',
    domain: 'Governance',
    title: '权限列表',
    method: 'GET',
    path: '/governance/permissions',
  },
  {
    id: 'governance-create-principle',
    domain: 'Governance',
    title: '创建原则',
    method: 'POST',
    path: '/governance/principles',
    bodyTemplate: {
      name: 'least privilege',
      description: 'Prefer minimum required authority',
      evaluation_logic: {},
      priority: 10,
    },
  },
  {
    id: 'governance-list-principles',
    domain: 'Governance',
    title: '原则列表',
    method: 'GET',
    path: '/governance/principles',
  },
  {
    id: 'governance-get-principle',
    domain: 'Governance',
    title: '原则详情',
    method: 'GET',
    path: '/governance/principles/{id}',
    pathParams: [{ name: 'id', label: '原则 ID' }],
  },
  {
    id: 'governance-create-rule',
    domain: 'Governance',
    title: '创建控制规则',
    method: 'POST',
    path: '/governance/control-rules',
    bodyTemplate: {
      principle_id: null,
      target_entity_type: 'workflow',
      target_entity_id: null,
      condition: {},
      action: 'notify',
      priority: 1,
    },
  },
  {
    id: 'governance-list-rules',
    domain: 'Governance',
    title: '控制规则列表',
    method: 'GET',
    path: '/governance/control-rules',
  },
  {
    id: 'governance-check',
    domain: 'Governance',
    title: '权限检查',
    method: 'POST',
    path: '/governance/check',
    bodyTemplate: {
      user_id: '',
      action: 'execute',
      resource: 'workflow',
      resource_id: null,
    },
  },
  {
    id: 'governance-access-decide',
    domain: 'Governance',
    title: '准入决策',
    method: 'POST',
    path: '/governance/access/decide',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      action: 'workflow.assign',
      resource: 'workflow_task',
      resource_id: null,
      organization_id: null,
      department_id: null,
      workflow_id: null,
      task_id: null,
      capability_id: null,
      required_level: 'L2',
      risk_level: 'medium',
      weight_snapshot: 0.65,
      context: {},
    },
  },
  {
    id: 'governance-access-decisions',
    domain: 'Governance',
    title: '准入审计列表',
    method: 'GET',
    path: '/governance/access/decisions',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-compute-weight',
    domain: 'Evolution',
    title: '计算权重',
    method: 'POST',
    path: '/evolution/weights/compute',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'human',
      task_context: {},
      required_level: 'L2',
    },
  },
  {
    id: 'evolution-record-outcome',
    domain: 'Evolution',
    title: '记录结果',
    method: 'POST',
    path: '/evolution/weights/outcome',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'human',
      outcome_score: 0.8,
      task_context: {},
    },
  },
  {
    id: 'evolution-get-weight',
    domain: 'Evolution',
    title: '权重详情',
    method: 'GET',
    path: '/evolution/weights/{actorType}/{actorID}',
    pathParams: [
      { name: 'actorType', label: '参与者类型', placeholder: 'human | ai' },
      { name: 'actorID', label: '参与者 ID' },
    ],
  },
  {
    id: 'evolution-compute-context-weight',
    domain: 'Evolution',
    title: '计算上下文权重',
    method: 'POST',
    path: '/evolution/context-weights/compute',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      required_level: 'L2',
      scope: {
        organization_id: null,
        department_id: null,
        workflow_template_id: null,
        workflow_stage: 'review',
        task_type: 'review launch readiness',
        capability_id: null,
        risk_level: 'medium',
        context: {},
      },
    },
  },
  {
    id: 'evolution-record-context-outcome',
    domain: 'Evolution',
    title: '记录上下文结果',
    method: 'POST',
    path: '/evolution/context-weights/outcome',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      outcome_score: 0.85,
      scope: {
        organization_id: null,
        department_id: null,
        workflow_template_id: null,
        workflow_stage: 'review',
        task_type: 'review launch readiness',
        capability_id: null,
        risk_level: 'medium',
        context: {},
      },
    },
  },
  {
    id: 'evolution-list-context-weights',
    domain: 'Evolution',
    title: '上下文权重列表',
    method: 'GET',
    path: '/evolution/context-weights',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-list-weights',
    domain: 'Evolution',
    title: '权重列表',
    method: 'GET',
    path: '/evolution/weights',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-get-alpha',
    domain: 'Evolution',
    title: 'Alpha 配置',
    method: 'GET',
    path: '/evolution/alphas',
  },
  {
    id: 'evolution-update-alpha',
    domain: 'Evolution',
    title: '更新 Alpha',
    method: 'PUT',
    path: '/evolution/alphas',
    bodyTemplate: {
      alpha_expertise: 0.25,
      alpha_track_record: 0.2,
      alpha_reliability: 0.15,
      alpha_recency: 0.1,
      alpha_context_fit: 0.1,
      alpha_principle: 0.2,
    },
  },
  {
    id: 'evolution-create-experiment',
    domain: 'Evolution',
    title: '创建实验',
    method: 'POST',
    path: '/evolution/experiments',
    bodyTemplate: {
      name: 'Routing alpha test',
      hypothesis: 'Higher reliability weight improves review quality',
      mvru_id: null,
      alpha_overrides: {},
      success_criteria: {},
    },
  },
  {
    id: 'evolution-list-experiments',
    domain: 'Evolution',
    title: '实验列表',
    method: 'GET',
    path: '/evolution/experiments',
  },
  {
    id: 'evolution-update-experiment',
    domain: 'Evolution',
    title: '更新实验状态',
    method: 'PATCH',
    path: '/evolution/experiments/{id}',
    pathParams: [{ name: 'id', label: '实验 ID' }],
    bodyTemplate: {
      status: 'running',
      conclusion: '',
    },
  },
  {
    id: 'evolution-create-knowledge',
    domain: 'Evolution',
    title: '创建知识',
    method: 'POST',
    path: '/evolution/knowledge',
    bodyTemplate: {
      workflow_id: null,
      title: 'Review heuristic',
      content: 'High risk changes should receive L2 review.',
      tags: ['review', 'risk'],
      source: 'manual',
    },
  },
  {
    id: 'evolution-list-knowledge',
    domain: 'Evolution',
    title: '知识列表',
    method: 'GET',
    path: '/evolution/knowledge',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-create-signal',
    domain: 'Evolution',
    title: '创建信号',
    method: 'POST',
    path: '/evolution/signals',
    bodyTemplate: {
      signal_type: 'metric_shift',
      source: 'manual',
      priority: 5,
      data: {},
    },
  },
  {
    id: 'evolution-list-signals',
    domain: 'Evolution',
    title: '信号列表',
    method: 'GET',
    path: '/evolution/signals',
    queryParams: [
      { name: 'acknowledged', label: '已确认', placeholder: 'true | false' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'evolution-ack-signal',
    domain: 'Evolution',
    title: '确认信号',
    method: 'POST',
    path: '/evolution/signals/{id}/acknowledge',
    pathParams: [{ name: 'id', label: '信号 ID' }],
  },
  {
    id: 'requirement-create',
    domain: 'Requirement',
    title: '创建需求',
    method: 'POST',
    path: '/requirements',
    bodyTemplate: {
      title: '业务流程自动化需求',
      description: '从需求拆解到项目交付与反馈评估',
      source: 'manual',
      priority: 'medium',
      risk_level: 'medium',
      required_level: 'L2',
      organization_id: null,
      department_id: null,
      metadata: {},
    },
  },
  {
    id: 'requirement-list',
    domain: 'Requirement',
    title: '需求列表',
    method: 'GET',
    path: '/requirements',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'requirement-get',
    domain: 'Requirement',
    title: '需求详情',
    method: 'GET',
    path: '/requirements/{id}',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-update',
    domain: 'Requirement',
    title: '更新需求',
    method: 'PATCH',
    path: '/requirements/{id}',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      status: 'analyzed',
      priority: 'high',
      risk_level: 'medium',
      required_level: 'L2',
      metadata: {},
    },
  },
  {
    id: 'requirement-analyze',
    domain: 'Requirement',
    title: '分析需求',
    method: 'POST',
    path: '/requirements/{id}/analyze',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      notes: 'agent assisted requirement analysis',
    },
  },
  {
    id: 'requirement-approve',
    domain: 'Requirement',
    title: '审批需求',
    method: 'POST',
    path: '/requirements/{id}/approve',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {},
  },
  {
    id: 'requirement-documents',
    domain: 'Requirement',
    title: '需求文档列表',
    method: 'GET',
    path: '/requirements/{id}/documents',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-start-analysis-workflow',
    domain: 'Requirement',
    title: '启动分析流程',
    method: 'POST',
    path: '/requirements/{id}/analysis-workflows',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      workflow_template_id: '',
      purpose: 'requirement_analysis',
      context: {},
      metadata: {},
    },
  },
  {
    id: 'requirement-list-analysis-workflows',
    domain: 'Requirement',
    title: '分析流程列表',
    method: 'GET',
    path: '/requirements/{id}/analysis-workflows',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-sync-analysis-workflow',
    domain: 'Requirement',
    title: '同步分析结果',
    method: 'POST',
    path: '/requirements/{id}/analysis-workflows/{workflowID}/sync',
    pathParams: [
      { name: 'id', label: '需求 ID' },
      { name: 'workflowID', label: '工作流 ID' },
    ],
    bodyTemplate: {},
  },
  {
    id: 'requirement-convert',
    domain: 'Requirement',
    title: '需求转项目',
    method: 'POST',
    path: '/requirements/{id}/convert-to-project',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      budget_amount: 5000,
      metadata: {},
    },
  },
  {
    id: 'project-create',
    domain: 'Project',
    title: '创建项目',
    method: 'POST',
    path: '/projects',
    bodyTemplate: {
      requirement_id: null,
      organization_id: null,
      department_id: null,
      name: '需求驱动交付项目',
      description: '项目过程管控、交付、成本核算和反馈评估',
      status: 'planning',
      priority: 'medium',
      risk_level: 'medium',
      required_level: 'L2',
      budget_amount: 5000,
      metadata: {},
    },
  },
  {
    id: 'project-list',
    domain: 'Project',
    title: '项目列表',
    method: 'GET',
    path: '/projects',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'project-get',
    domain: 'Project',
    title: '项目详情',
    method: 'GET',
    path: '/projects/{id}',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-overview',
    domain: 'Project',
    title: '项目总览',
    method: 'GET',
    path: '/projects/{id}/overview',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-update',
    domain: 'Project',
    title: '更新项目',
    method: 'PATCH',
    path: '/projects/{id}',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      name: 'Updated project',
      status: 'active',
      budget_amount: 8000,
      metadata: {},
    },
  },
  {
    id: 'project-status',
    domain: 'Project',
    title: '更新项目状态',
    method: 'POST',
    path: '/projects/{id}/status',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      status: 'delivering',
      note: 'process checkpoint',
    },
  },
  {
    id: 'project-add-member',
    domain: 'Project',
    title: '添加项目成员',
    method: 'POST',
    path: '/projects/{id}/members',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      member_actor_id: '',
      member_actor_type: 'internal_human',
      position_id: null,
      position_assignment_id: null,
      role: 'owner',
      title: 'Project Owner',
      allocation_percent: 100,
      cost_rate: 800,
      permission_level: 'L2',
      capabilities: ['planning', 'delivery', 'review'],
      metadata: {},
    },
  },
  {
    id: 'project-list-members',
    domain: 'Project',
    title: '项目成员',
    method: 'GET',
    path: '/projects/{id}/members',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-bind-workflow',
    domain: 'Project',
    title: '绑定项目流程',
    method: 'POST',
    path: '/projects/{id}/workflows',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      workflow_id: null,
      workflow_template_id: null,
      purpose: 'delivery',
      metadata: {},
    },
  },
  {
    id: 'project-match-actors',
    domain: 'Project',
    title: '匹配项目成员',
    method: 'POST',
    path: '/projects/{id}/match-actors',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      task_description: '需求拆解、执行交付与人工验收',
      required_capabilities: ['planning', 'delivery', 'review'],
      required_level: 'L2',
      risk_level: 'medium',
      member_types: ['internal', 'external', 'agent'],
    },
  },
  {
    id: 'delivery-create',
    domain: 'Delivery',
    title: '创建交付物',
    method: 'POST',
    path: '/projects/{id}/deliverables',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      name: '交付物 v1',
      deliverable_type: 'document',
      uri: '',
      version: '1.0',
      status: 'draft',
      metadata: {},
    },
  },
  {
    id: 'delivery-list',
    domain: 'Delivery',
    title: '交付物列表',
    method: 'GET',
    path: '/projects/{id}/deliverables',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'delivery-update',
    domain: 'Delivery',
    title: '更新交付物',
    method: 'PATCH',
    path: '/deliverables/{id}',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: {
      name: 'Updated deliverable',
      status: 'draft',
      metadata: {},
    },
  },
  {
    id: 'delivery-submit',
    domain: 'Delivery',
    title: '提交交付物',
    method: 'POST',
    path: '/deliverables/{id}/submit',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: { evidence: {} },
  },
  {
    id: 'delivery-accept',
    domain: 'Delivery',
    title: '验收交付物',
    method: 'POST',
    path: '/deliverables/{id}/accept',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: { evidence: {} },
  },
  {
    id: 'delivery-reject',
    domain: 'Delivery',
    title: '退回交付物',
    method: 'POST',
    path: '/deliverables/{id}/reject',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: {
      reason: 'needs revision',
      evidence: {},
    },
  },
  {
    id: 'cost-create',
    domain: 'Cost',
    title: '写入成本',
    method: 'POST',
    path: '/projects/{id}/cost-entries',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      source_type: 'manual',
      entry_actor_id: null,
      entry_actor_type: 'internal_human',
      amount: 1000,
      currency: 'CNY',
      description: 'manual cost entry',
      metadata: {},
    },
  },
  {
    id: 'cost-list',
    domain: 'Cost',
    title: '成本明细',
    method: 'GET',
    path: '/projects/{id}/cost-entries',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'cost-summary',
    domain: 'Cost',
    title: '成本汇总',
    method: 'GET',
    path: '/projects/{id}/cost-summary',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'cost-refresh',
    domain: 'Cost',
    title: '刷新成员成本',
    method: 'POST',
    path: '/projects/{id}/cost-refresh',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {},
  },
  {
    id: 'feedback-create',
    domain: 'Feedback',
    title: '创建项目评估',
    method: 'POST',
    path: '/projects/{id}/evaluations',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      evaluated_actor_id: null,
      evaluated_actor_type: 'internal_human',
      capability_id: null,
      quality_score: 0.8,
      delivery_score: 0.8,
      cost_score: 0.75,
      collaboration_score: 0.8,
      conclusion: 'human-reviewed project delivery',
      evidence: {},
    },
  },
  {
    id: 'feedback-list',
    domain: 'Feedback',
    title: '项目评估列表',
    method: 'GET',
    path: '/projects/{id}/evaluations',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'feedback-close',
    domain: 'Feedback',
    title: '闭环反馈',
    method: 'POST',
    path: '/projects/{id}/close-feedback',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      outcome_score: 0.8,
      conclusion: 'project closed with feedback',
      metadata: {},
    },
  },
]

export const operationDomains = Array.from(new Set(apiOperations.map((operation) => operation.domain)))
